#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
  # 多的主题，你可以载入 colorscheme 模块
  # colorscheme = "molokai"
  # colorscheme = "srcery"
  # colorscheme = "onedark"
  # colorscheme = "jellybeans"
  # colorscheme = "palenight"
  # colorscheme = "one"
  # colorscheme = "nord"
  # colorscheme = "gruvbox"
  # colorscheme = "NeoSolarized"
  # colorscheme = "hybrid"
  # colorscheme = "material"
  colorscheme = "SpaceVim"

  # 背景可以取值 "dark" 或 "light"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
  # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
  # 可以禁用终端真色，将下面的值设为 false
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
  # 禁用分割符号，默认为箭头 "arrow"
  # arrow | curve | slant | nil | fire
  # |||||>| ||||) | ||||\ | ||| | >||>
  statusline_separator = "fire"
  # 设置非活动窗口状态栏上的分割符号形状
  statusline_iseparator = "arrow"

  # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
  # 0: 1 ➛ ➊
  # 1: 1 ➛ ➀
  # 2: 1 ➛ ⓵
  # 3: 1 ➛ ¹
  # 4: 1 ➛ 1
  buffer_index_type = 4

  # 显示/隐藏顶部标签栏上的文件类型图标，这一图标需要安装 nerd fonts，
  # 如果未能成功安装这一字体，可以隐藏图标
  enable_tabline_filetype_icon = true
  # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
  # 字样，只以颜色区分当前模式
  enable_statusline_mode = false

   # 状态栏左端部分的构成
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
  # 状态栏右端部分的构成
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time', 'battery status']
  # 列表可以由以下一项或多项组成
  # 'winnr' 当前窗口编号
  # 'syntax checking'
  # 'filename' 文件名
  # 'fileformat' 文件格式
  # 'major mode'
  # 'minor mode lighters'
  # 'cursorpos' 光标位置
  # 'percentage' 百分比
  # 'date' 日期
  # 'time' 时间
  # 'whitespace' 打开或者保存文件时，如果第 n 行的行尾有空格则显示 trailing[n]，并不能实时显示出行尾有空格的行号。
  # 'battery status' 电池状态
  # 'input method' 输入法
  # 'search status' 搜索状态

  # 文件树插件可选值包括：
  # - vimfiler （默认）
  # - nerdtree
  # - defx
  filemanager = "defx"
  vim_help_language = "cn"

# SpaceVim 模块设置，主要包括启用/禁用模块

# Enable autocomplete layer
# 启用 autocomplete 模块，启用模块时，可以列出一些模块选项，并赋值，
# 关于模块的选项，请阅读各个模块的文档
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  # cycle | smart | ...
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "format"
  
[[layers]]
  name = 'lsp'
  filetypes = [
    # 'c',
    # 'cpp',
    'css',
    # 'dart',
    # 'html',
    'javascript',
    # 'kotlin',
    # 'objc',
    # 'objcpp',
    # 'python',
    # 'ruby',
    'sh',
    # 'typescript',
    'vue',
  ]
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for c, clangd is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for cpp, clangd is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for dart, dart_language_server is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for html, html-languageserver is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for objc, clangd is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for objcpp, clangd is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for python, pyls is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for ruby, solargraph is not executable!
# [ SpaceVim ] [01:00:26] [ Warn ] Failed to enable lsp for typescript, typescript-language-server is not executable!

# [[layers]]
  # name = "chat"

[[layers]]
  name = "chinese"

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'cscope'

[[layers]]
  name = "foldsearch"
  foldsearch_highlight = true

[[layers]]
  name = "format"
  enable = true
  format_on_save = false

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#cpp"

[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#dockerfile"
  
[[layers]]
  name = "lang#go"
  
[[layers]]
  name = "lang#graphql"
  
[[layers]]
  name = "lang#groovy"
  
[[layers]]
  name = "lang#html"
  
[[layers]]
  name = "lang#java"
  
[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#kotlin"
  enable_native_support = true

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#swift"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

# 禁用 shell 模块，禁用模块时，需要加入 enable = false
# enable = false
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "sudo"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = "tools#dash"

[[layers]]
  name = "tools"

[[layers]]
  name = "ui"

# 添加自定义插件
[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = false

# add custom_plugins: https://github.com/awc/SpaceVim-theme
[[custom_plugins]]
  repo = "awc/SpaceVim-theme"
  merged = false
